apiVersion: v2
name: oom-autofix-operator
description: Auto-detects OOMKilled pods and patches Deployment memory limits from 400Mi → 900Mi
type: application
version: 0.1.2
appVersion: "0.1.2"
kubeVersion: ">=1.24.0-0"
home: https://github.com/sanket-gawali/oom-autofix-operator
icon: https://artifacthub.io/static/media/placeholder_pkg_helm.png
sources:
  - https://github.com/sanket-gawali/oom-autofix-operator
maintainers:
  - name: Sanket Gawali
    email: sanket@example.com
keywords:
  - kubernetes
  - operator
  - kopf
  - oom
  - memory
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/sanket-gawali/oom-autofix-operator
  artifacthub.io/images: |
    - name: operator-runtime
      image: python:3.12-slim
      platforms:
        - linux/amd64
        - linux/arm64
