apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oom-autofix-operator.fullname" . }}-operator-script
  labels:
    {{- include "oom-autofix-operator.labels" . | nindent 4 }}
data:
  operator.py: |
{{ .Files.Get "files/operator.py" | nindent 4 }}
